services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: resumes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/resumes
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      UPLOAD_DIR: /data/uploads
    volumes:
      - ./backend:/app
      - uploads:/data/uploads
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE: http://localhost:8000
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: ["sh", "-c", "npm install --silent --no-audit --no-fund --legacy-peer-deps && npm run dev -- --host 0.0.0.0"]


volumes:
  db_data:
  uploads:
